[dependencies]
array = "https://github.com/aviate-labs/array.mo#v0.2.1"
"base-0.7.3" = "https://github.com/dfinity/motoko-base#aafcdee0c8328087aeed506e64aa2ff4ed329b47"
crypto = "https://github.com/aviate-labs/crypto.mo#v0.3.1"
hash = "https://github.com/aviate-labs/hash.mo#v0.1.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
base = "0.11.1"
fuzz = "0.2.1"